name: lightEconomy
author: lightPlugins
version: 5.4.5
main: de.lightplugins.economy.master.Main
api-version: 1.17
depend: [Vault, ]
softdepend: [PlaceholderAPI, TheNewEconomy, ProtocolLib]
loadbefore: [Essentials, Towny]
commands:
  le:
    description: The root command for administrated things
    aliases: [lighteconomy, lighteco, leco]
  money:
    description: The root command for admin things
    aliases: [mon]
  balance:
    description: The root command for user things
    aliases: [bal]
  eco:
    description: Console only commands
    aliases: []
  pay:
    description: Give other players some money from your own pocket
    aliases: []
  bank:
    description: The bank command
    aliases: []
