name: lightEconomy
author: lightPlugins
version: 5.4.0
main: de.lightplugins.economy.master.Main
api-version: 1.17
depend: [Vault]
softdepend: [PlaceholderAPI]
loadbefore: [Essentials, Towny]
commands: {
            le:,
            money:,
            eco:,
            pay:,
            bank:,
}
