name: lightEconomyV5
author: lightPlugins
version: 5.0.0
main: de.lightplugins.economy.master.Main
api-version: 1.19
depend: [Vault]
loadbefore: [Essentials, Towny]
commands: {
            le:,
            money:,
            eco:,
            pay:,
}
