#
#  $$\ $$\           $$\        $$\     $$$$$$$$\
#  $$ |\__|          $$ |       $$ |    $$  _____|
#  $$ |$$\  $$$$$$\  $$$$$$$\ $$$$$$\   $$ |      $$$$$$$\  $$$$$$\  $$$$$$$\   $$$$$$\  $$$$$$\$$$$\  $$\   $$\
#  $$ |$$ |$$  __$$\ $$  __$$\\_$$  _|  $$$$$\   $$  _____|$$  __$$\ $$  __$$\ $$  __$$\ $$  _$$  _$$\ $$ |  $$ |
#  $$ |$$ |$$ /  $$ |$$ |  $$ | $$ |    $$  __|  $$ /      $$ /  $$ |$$ |  $$ |$$ /  $$ |$$ / $$ / $$ |$$ |  $$ |
#  $$ |$$ |$$ |  $$ |$$ |  $$ | $$ |$$\ $$ |     $$ |      $$ |  $$ |$$ |  $$ |$$ |  $$ |$$ | $$ | $$ |$$ |  $$ |
#  $$ |$$ |\$$$$$$$ |$$ |  $$ | \$$$$  |$$$$$$$$\\$$$$$$$\ \$$$$$$  |$$ |  $$ |\$$$$$$  |$$ | $$ | $$ |\$$$$$$$ |
#  \__|\__| \____$$ |\__|  \__|  \____/ \________|\_______| \______/ \__|  \__| \______/ \__| \__| \__| \____$$ |
#          $$\   $$ |                                                                                  $$\   $$ |
#          \$$$$$$  |                                                                                  \$$$$$$  |
#           \______/                                                                                    \______/
#
#
#               Plugin version 5.0
#               Developer: lightPlugins
#
version: 5.0
mysql:
  # if disabled, the plugin will use automatically sqlite for single server setup
  enable: true
  host: 136.243.208.18
  port: 3306
  database: lightEconomy
  user: lightEconomy
  password: KPCDrfYC2uPrIlc9X3V4X0LIV9aQZRbu
  ssl: false
settings:
  # Debug Messages in the log
  debug: true
  date-format: 'dd:mm:yyyy'
  pay-command-delay: 10
  currency-name-plural: 'EUR'
  currency-name-singular: 'EURs'
  max-pocket-balance: 999999999999,99
  baltop-amount-of-players: 10
  baltop-exclude:
    - gaben
    - notch